projects:
  lightgramApi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: yblb7fjf55d2hbuaebyye7zwzi
      endpoints:
        prod: >-
          https://ir4uwwxltremnnzdrksqgtmxye.appsync-api.us-east-1.amazonaws.com/graphql
