// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9a0e16e3-6bb1-48b0-addc-6cd21f68f8d0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ELIBkvDdb",
    "aws_user_pools_web_client_id": "5mt9hg56hq5s51con4vq8reqk9"
};


export default awsmobile;
